# Generated by Django 3.1.3 on 2020-11-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformsuser',
            name='form_id',
            field=models.UUIDField(default=None, verbose_name='ID формы'),
        ),
    ]
